version: '3.4'

services:
        node-app:
                build:
                        context: .
                        target: development
                volumes:
                        - .:/app
                environment:
                        - NODE_ENV=development
                command: npm run start-dev
