version: '3.4'

services:
        node-app:
                depends_on:
                        - postgres-db
                        - mongo
                        - redis
                restart: always
                container_name: node-app
                ports:
                        - "4000:4000"
                env_file:
                        - ./.env
        mongo:
                image: mongo
                restart: always
                container_name: mongo
                volumes:
                        - mongo-db:/data/db
                environment:
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: example

                        
        mongo-express:
                image: mongo-express
                depends_on:
                        - mongo
                restart: always
                container_name: mongo-express
                ports:
                        - 8081:8081
                environment:
                        ME_CONFIG_MONGODB_ADMINUSERNAME: root
                        ME_CONFIG_MONGODB_ADMINPASSWORD: example
                        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/                        
                        
        redis:
                image: redis
                restart: always
                container_name: redis
        nginx:
                depends_on:
                        - node-app
                restart: always
                container_name: nginx
                image: nginx:stable-alpine
                ports:
                        - "80:80"
                volumes:
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        postgres-db:
                image: postgres
                restart: always
                container_name: postgres-db
                volumes:
                        - postgres-db:/var/lib/postgresql/data
                environment:
                        POSTGRES_USER: root
                        POSTGRES_PASSWORD: example

volumes:
        mongo-db:
        postgres-db:
